import type { Metadata } from "next";
import "./globals.css";
import {ThemeProvider} from '@/components/theme-provider'
import Navbar from "@/components/navbar";
import localFont from 'next/font/local';


const jetbrainsMono = localFont({
  src: [
    {
      path: "../public/fonts/jetbrains_mono/static/JetBrainsMono-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/jetbrains_mono/static/JetBrainsMono-Bold.ttf",
      weight: "700",
      style: "normal",
    }
  ],
  variable: "--font-jetbrains-mono"
});

const sans = localFont({
  variable: "--font-sans",
  src: [
    {path: "../public/fonts/Google_Sans/static/GoogleSans-Regular.ttf", weight: "400", style: "normal"},
    {path: "../public/fonts/Google_Sans/static/GoogleSans-Bold.ttf", weight: "700", style: "normal"}
  ]
});

const dancingScript = localFont({
  variable: "--font-dancing-script",
  src: [
    {path: "../public/fonts/Dancing_Script/static/DancingScript-Regular.ttf", weight: "400", style: "normal"},
    {path: "../public/fonts/Dancing_Script/static/DancingScript-Bold.ttf", weight: "700", style: "normal"}
  ]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jetbrainsMono.variable} ${sans.variable} ${dancingScript.variable} h-full antialiased min-w-87.5 dark:bg-background dark:text-foreground`}
      suppressHydrationWarning>
      
        <body className="min-h-full flex flex-col">
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </body>

    </html>
  );
}
